"""
Django settings for modeller_web project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure the root folder with smosh is in sys.path
SMOSH_PARENT_DIR = str(BASE_DIR.parent)
if SMOSH_PARENT_DIR not in sys.path:
    sys.path.insert(0, SMOSH_PARENT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$lbtkw0k*yatraj$i+tov)7(2apyc=!pk2ll_2l1%p5^la8wx@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'experiments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'modeller_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'experiments.context_processors.site_language',
            ],
        },
    },
]

WSGI_APPLICATION = 'modeller_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'experiment_list'
LOGOUT_REDIRECT_URL = 'home'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Autenticação por e-mail
AUTHENTICATION_BACKENDS = [
    'experiments.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Configuração do ambiente Modeller 10.7 (chave e caminhos das bibliotecas nativas C / Python)
KEY_MODELLER = os.environ.get('KEY_MODELLER', 'MODELIRANJE')
os.environ['KEY_MODELLER'] = KEY_MODELLER

MODELLER_INSTALL = os.environ.get('MODINSTALL10v7', '/usr/lib/modeller10.7')
MODELLER_LIB = os.path.join(MODELLER_INSTALL, 'lib', 'x86_64-intel8')
MODELLER_PY33 = os.path.join(MODELLER_LIB, 'python3.3')
MODELLER_MODLIB = os.path.join(MODELLER_INSTALL, 'modlib')

# No Python 3, precisamos do _modeller.so de python3.3 e dos módulos de modlib
for _p in [MODELLER_PY33, MODELLER_MODLIB]:
    if os.path.isdir(_p) and _p not in sys.path:
        sys.path.insert(0, _p)
if MODELLER_LIB in sys.path:
    sys.path.remove(MODELLER_LIB)

_curr_pp = os.environ.get('PYTHONPATH', '')
_pp_list = [p for p in [MODELLER_PY33, MODELLER_MODLIB] if os.path.isdir(p)]
if _curr_pp:
    _pp_list.extend([p for p in _curr_pp.split(':') if p and p != MODELLER_LIB])
os.environ['PYTHONPATH'] = ':'.join(_pp_list)

_curr_ld = os.environ.get('LD_LIBRARY_PATH', '')
_ld_list = [p for p in [MODELLER_LIB] if os.path.isdir(p)]
if _curr_ld:
    _ld_list.extend([p for p in _curr_ld.split(':') if p and p != MODELLER_LIB])
os.environ['LD_LIBRARY_PATH'] = ':'.join(_ld_list)

